const actOrder = {
  GET_RESERVATION: 'GET_RESERVATION',
  GET_RESERVATION_SUCCESS: 'GET_RESERVATION_SUCCESS',
  GET_RESERVATION_FAILURE: 'GET_RESERVATION_FAILURE',
  GET_TABLE: 'GET_TABLE',
  GET_TABLE_SUCCESS: 'GET_TABLE_SUCCESS',
  GET_TABLE_FAILURE: 'GET_TABLE_FAILURE',
  SET_LOADING: 'SET_LOADING',
  SET_LOADING_SUCCESS: 'SET_LOADING_SUCCESS',
  SET_LOADING_FAILURE: 'SET_LOADING_FAILURE',
}

export default actOrder
